[project]
name = "toolbox-continu-inzicht"
version = "0.1.1"
description = "Toolbox voor waterkeringbeheerders om risico's in kaart te brengen."
channels = ["conda-forge"]
platforms = ["win-64", "linux-64"]
readme = "README.md"
license = "GPL-3.0"
license-file = "LICENSE"
repository = "https://github.com/continu-inzicht/toolbox-continu-inzicht"
homepage = "https://continu-inzicht.github.io/toolbox-continu-inzicht/"

[tasks]
# Installation
install = "pre-commit install"

# Docs
quartodoc-build = { cmd = "quartodoc build && rm objects.json", cwd = "docs" ,inputs = [
    "docs/_quarto.yml",
    "src/continu_inzicht_toolbox",
    ],outputs = [
    "docs/reference/"
    ]}

quartodoc-build-force = { cmd = "quartodoc build && rm objects.json", cwd = "docs" ,inputs = [
    "docs/_quarto.yml",
    "src/continu_inzicht_toolbox",
] }
quarto-preview = { cmd = "export QUARTO_PYTHON=python && quarto preview docs", depends-on = [
    "quartodoc-build",
] }
quarto-check = { cmd = "quarto check all", depends-on = ["quartodoc-build"] }
quarto-render = { cmd = "export QUARTO_PYTHON=python && quarto render docs --to html --execute", depends-on = [
    "quartodoc-build",
] }
# Lint
pre-commit = "pre-commit run --all-files"
lint = { depends-on = ["pre-commit"] }
# Test
pytest-cov = "pytest --cov --cov-report=xml --benchmark-save=ci-run --ignore=src\\toolbox_continu_inzicht\\base\\adapters"
pytest-cov-html = "pytest --cov --cov-report html:tests/hidden_test_cov --ignore=src\\toolbox_continu_inzicht\\base\\adapters"

[feature.common.dependencies]
contextily = "*"
fiona = "*"
geopandas = "*"
ipykernel = "*"
ipywidgets = ">=8.1.5,<9"
jupyter-cache = ">=1.0.0,<2"
jupyterlab = "*"
matplotlib = "*"
netcdf4 = ">=1.7.1,<2"
openpyxl = "*"
openturns = ">=1.23,<2"
pandas = "*"
pandas-stubs = "*"
pip = "*"
pre-commit = "*"
psycopg2 = "*"
pyarrow = "*"
pydantic = ">=2"
pyogrio = "*"
pytest = "*"
pytest-benchmark = "*"
pytest-cov = "*"
pytest-xdist = "*"
python = ">=3.10"
python-dotenv = ">=1.0.1,<2"
quarto = "*"
quartodoc = "<=0.9.0"
requests = "*"
ruff = "*"
shapely = ">=2"
httpx = "<0.28.0"
sqlalchemy = "*"
tomli = "*"
tomli-w = "*"
tqdm = ">=4.67.1,<5"
types-requests = "*"
types-pyyaml = "*"
xugrid = "*"
yaml = "*"
grayskull = "*"
geoalchemy2 = ">=0.17.1,<0.18"

[feature.common.pypi-dependencies]
toolbox_continu_inzicht = { path = "src", editable = true }
pydra-core = "==0.0.9"
probabilistic-piping = "==0.0.5"

[environments]
default = { features = ["common"] }
