[project]
name = "continu-inzicht-toolbox"
version = "0.0.1"
description = "Toolbox voor waterkeringbeheerders om risico's in kaart te brengen."
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64"]
readme = "README.md"
license = "GPL-3.0"
license-file = "LICENSE"

[tasks]
# Installation
install = "pre-commit install"

# Docs
quartodoc-build = { cmd = "quartodoc build && rm objects.json", cwd = "docs" ,inputs = [
    "docs/_quarto.yml",
    "src/continu_inzicht_toolbox",
    ],outputs = [
    "docs/reference/"
    ]}
quarto-preview = { cmd = "export QUARTO_PYTHON=python && quarto preview docs", depends_on = [
    "quartodoc-build",
] }
quarto-check = { cmd = "quarto check all", depends_on = ["quartodoc-build"] }
quarto-render = { cmd = "export QUARTO_PYTHON=python && quarto render docs --to html --execute", depends_on = [
    "quartodoc-build",
] }
docs = { depends_on = ["build-julia-docs", "quarto-preview"] }

# Lint
pre-commit = "pre-commit run --all-files"
lint = { depends_on = ["pre-commit"] }
# Test


[feature.common.dependencies]
bokeh = ">=3.0"
contextily = "*"
fiona = "*"
geocube = "*"
geopandas = "*"
ipykernel = "*"
jupyterlab = "*"
matplotlib = "*"
mypy = "*"
openpyxl = "*"
pandas = "*"
pandas-stubs = "*"
pandera = "*"
pip = "*"
pre-commit = "*"
pyarrow = "*"
pydantic = ">=2"
pyogrio = "*"
pytest = "*"
pytest-cov = "*"
pytest-xdist = "*"
python = ">=3.9"
quarto = "*"
quartodoc = "*"
rasterstats = "*"
requests = "*"
ruff = "*"
shapely = ">=2"
tomli = "*"
tomli-w = "*"
types-requests = "*"
xugrid = "*"

[feature.common.pypi-dependencies]
continu_inzicht_toolbox = { path = "src/continu_inzicht_toolbox", editable = true }


[environments]
default = { features = ["common"] }

[dependencies]
yaml = ">=0.2.5,<0.3"
sqlalchemy = ">=2.0.34,<3"
types-pyyaml = ">=6.0.12.20240808,<7"
psycopg2 = ">=2.9.9,<3"
