
global_variables:
    rootdir: 'C:\Data\Python\toolbox-continu-inzicht\docs\examples\notebooks'

# functie naam
WaardesDelenTwee:
    input: 
        type: csv
        path: '\data_sets\test_csv_out.csv'
    output: 
        type: csv
        path: 'data_sets\test_csv_out2.csv'

WaardesKeerTwee:
    input:
        type: postgresql_database
        table: data
    output: 
        type: postgresql_database
        table: data