global_variables:
    rootdir: 'docs\examples\notebooks'

WaardesDelenTwee: 
    input:
        type: postgresql_database
        table: data

    output: 
        type: csv
        path: 'data_sets\test_csv_out_mix.csv'
