global_variables:
    rootdir: 'C:\Data\Python\toolbox-continu-inzicht\docs\examples\notebooks'

WaardesKeerTwee: 
    input: 
        type: csv
        path: 'data_sets\test_csv_in.csv'
    output: 
        type: csv
        path: 'data_sets\test_csv_out.csv'

WaardesDelenTwee:
    input:
        type: postgresql_database
        table: data
    output: 
        type: postgresql_database
        table: data