GlobalVariables:
    rootdir: 'data_sets'
    postgresql_database:
        database: 'citoolbox'
        schema: 'citoolbox_schema'

DataAdapter:
    MyCSV_in: 
        type: csv
        file: 'test_csv_in.csv'
    MyCSV_out: 
        type: csv
        file: 'test_csv_out.csv'
    MyPostgresql: 
        type: postgresql_database
        table: data
    MyNetCDF_in:
        type: netcdf
        file: 'test_netcdf_in.nc'
    MyNetCDF_out:
        type: netcdf
        file: 'test_netcdf_out.nc'
