GlobalVariables:
    rootdir: 'data_sets'
    logging:
        name:  toolbox_continu_inzicht  # default
        level: DEBUG
        mode:  w # default
        file:  hidden_logfile_advanced.log

DataAdapter:
    mycsv_in:
        type: csv
        file: 'test_csv_in.csv'
    mycsv_out:
        type: csv
        file: 'test_csv_out.csv'
