project:
  type: website
  output-dir: docs

website:
  title: "Continu inzicht toolbox"
  navbar:
    logo: https://raw.githubusercontent.com/continu-inzicht/toolbox-continu-inzicht/main/docs/assets/logo.png
    left:
      - reference/index.qmd
    right:
      - icon: github
        href: https://github.com/continu-inzicht/toolbox
        aria-label: GitHub

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

quartodoc:
  style: pkgdown
  dir: reference
  title: API Reference
  package: continu_inzicht_toolbox
  # sections: 
  #   - title: Continu Inzicht
  #     contents: 
  #      - continu_inzicht_toolbox
  #      - base
  # # options:
  #   include_inherited: true
  #   include_empty: true
  #   include_attributes: true
  #   include_classes: true
  #   include_functions: true
  # # sections:
  #   - title: Continu inzicht toolbox
  #     desc: Toolbox voor continu inzicht
  #     package: continu_inzicht_toolbox
  #     content: 
  #      - PlaceHolder
