project:
  type: website
  output-dir: docs

website:
  title: "Toolbox continu inzicht"
  navbar:
    logo: https://raw.githubusercontent.com/continu-inzicht/toolbox-continu-inzicht/main/docs/assets/logo.png
    left:
      - text: "Installeren"
        file:  install.qmd
      - text: "Voorbeelden"
        file: examples/notebooks/proof_of_concept.ipynb
      - text: "Modules"
        file:  modules.qmd
      - text: "Python API"
        file: reference/index.qmd
      - text: "Overig"
        file: contact.qmd

    right:
      - text: "Bijdragen"
        file: contributing.qmd
      - icon: github
        href: https://github.com/continu-inzicht/toolbox
        aria-label: GitHub

  sidebar:
      - title: "Installeren"
        contents:
          - install.qmd

      - title: "Voorbeelden"
        contents:
          - examples/notebooks/proof_of_concept.ipynb

      - title: "Modules"
        contents:
          - modules.qmd

      - title: "Python API"
        contents:
          - reference/index.qmd

      - title: "Overig"
        contents:
          - contact.qmd
          - tests.qmd
          - changelog.qmd

      - title: "Bijdragen"
        contents:
          - contributing.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




quartodoc:
  style: pkgdown
  dir: reference
  title: API Reference
  package: toolbox_continu_inzicht
  parser: numpy
  dynamic: True
  rewrite_all_pages: True
  options:
    include_inherited: true
    include_empty: true
    include_attributes: true
    include_classes: true
    include_functions: true
  sections:
    - title: Basis
      desc: Lees & schrijf functionaliteit waar andere functies op verder bouwen
      package: toolbox_continu_inzicht
      contents:
       - config
       - data_adapter
       - proof_of_concept.example_module
    - title: Belastingen
      desc: Verschillende functies die belastingen inladen, classifiseren of toekennen.
      package: toolbox_continu_inzicht
      contents:
       - loads.LoadsCIWhatIf
       - loads.LoadsClassify
       - loads.LoadsFews
       - loads.get_fews_locations
       - loads.get_fews_thresholds
       - loads.LoadsMatroos
       - loads.get_matroos_locations
       - loads.LoadsWaterwebservicesRWS
       - loads.get_rws_webservices_locations
       - loads.LoadsToMoments
       - loads.LoadsWaterinfo
       - loads.get_waterinfo_locations
       - loads.get_waterinfo_thresholds

      #  - base


          # - haal_waterstanden_op
          # - calculate_fragility_curves


  # # options:
  #   include_inherited: true
  #   include_empty: true
  #   include_attributes: true
  #   include_classes: true
  #   include_functions: true
  # # sections:
  #   - title: Continu inzicht toolbox
  #     desc: Toolbox voor continu inzicht
  #     package: continu_inzicht_toolbox
  #     content:
  #      - PlaceHolder
