project:
  type: website
  output-dir: docs

website:
  title: "Toolbox continu inzicht"
  navbar:
    logo: https://raw.githubusercontent.com/continu-inzicht/toolbox-continu-inzicht/main/docs/assets/logo.png
    left:
      - text: "Achtergrond"
        file: index.qmd
      - text: "Python documentatie"
        file: reference/index.qmd
      - text: "Voorbeelden"
        file: examples/notebooks/proof_of_concept.ipynb
    right:
      - text: "Bijdragen"
        file: contributing.qmd
      - icon: github
        href: https://github.com/continu-inzicht/toolbox
        aria-label: GitHub

  sidebar:
      - title: "Achtergrond"
        contents:
          - index.qmd
          - install.qmd
          - changelog.qmd

      - title: "Python documentatie"
        contents:
          - reference/index.qmd
      
      - title: "Voorbeelden"
        contents:
          - examples/notebooks/proof_of_concept.ipynb
        
      - title: "Bijdagen"
        contents:
          - contributing.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




quartodoc:
  style: pkgdown
  dir: reference
  title: API Reference
  package: toolbox_continu_inzicht
  dynamic: True
  rewrite_all_pages: True
  options:
    include_inherited: true
    include_empty: true
    include_attributes: true
    include_classes: true
    include_functions: true
  sections:  
    - title: Continu inzicht toolbox
      desc: Toolbox voor continu inzicht
      package: toolbox_continu_inzicht
      contents: 
       - base.config
       - base.data_adapter
       - proof_of_concept.voorbeeld_module
       - fragility_curves.calculate_fragility_curves
      #  - base
    
  
          # - haal_waterstanden_op
          # - calculate_fragility_curves
          
          
  # # options:
  #   include_inherited: true
  #   include_empty: true
  #   include_attributes: true
  #   include_classes: true
  #   include_functions: true
  # # sections:
  #   - title: Continu inzicht toolbox
  #     desc: Toolbox voor continu inzicht
  #     package: continu_inzicht_toolbox
  #     content: 
  #      - PlaceHolder
