project:
  type: website
  output-dir: docs

website:
  title: "Toolbox continu inzicht"
  navbar:
    logo: https://raw.githubusercontent.com/continu-inzicht/toolbox-continu-inzicht/main/docs/assets/logo.png
    left:
      - text: "Installeren"
        file:  install.qmd
      - text: "Voorbeelden"
        file: "examples/voorbeelden.qmd"
      - text: "Modules"
        file:  modules_index.qmd
      - text: "Python API"
        file: reference/index.qmd
      - text: "Overig"
        file: contact.qmd

    right:
      - text: "Bijdragen"
        file: contributing.qmd
      - icon: GitHub
        href: https://github.com/continu-inzicht/toolbox
        aria-label: GitHub

  sidebar:
      - title: "Installeren"
        contents:
          - install.qmd

      - title: "Voorbeelden"
        contents:
            - examples/notebooks/1.proof_of_concept.ipynb
            - examples/notebooks/2.belastingen_inladen.ipynb
            - examples/notebooks/3.fragility_curve_overtopping.ipynb
            - examples/notebooks/4.adjust_integrated_statistics.ipynb
            - examples/notebooks/5.Inspectie_resultaten.ipynb
            - examples/notebooks/6.WMS_laag_naar_database.ipynb

      - title: "Modules"
        contents:
          - modules_index.qmd
          - modules/architectuur.qmd
          - modules/belastingen.qmd
          - modules/bepalen_fragility_curves.qmd
          - modules/bijstellen_fragility_curves.qmd
          - modules/kansen_en_status_per_sectie.qmd
          - modules/impactanalyse.qmd
          - modules/inspectieresultaten.qmd

      - title: "Python API"
        contents:
          - reference/index.qmd

      - title: "Overig"
        contents:
          - contact.qmd
          - tests.qmd
          - changelog.qmd

      - title: "Bijdragen"
        contents:
          - contributing.qmd


format:
  html:
    theme: cosmo
    css: styles/styles.css
    toc: true
    encoding: 'ISO-8859-1'

quartodoc:
  style: pkgdown
  dir: reference
  title: API Reference
  package: toolbox_continu_inzicht
  parser: numpy
  dynamic: True
  rewrite_all_pages: True
  options:
    include_inherited: true
    include_empty: true
    include_attributes: true
    include_classes: true
    include_functions: true
  sections:
    - title: Basis
      desc: Basis functionaliteit waar andere functies op verder bouwen
      package: toolbox_continu_inzicht
      contents:
       - Config
       - DataAdapter
       - proof_of_concept.example_module
       - FragilityCurve
    - title: Belastingen
      desc: Functies die belastingen inladen, classificeren of toekennen.
      package: toolbox_continu_inzicht.loads
      contents:
       - LoadsCIWhatIf
       - LoadsClassify
       - LoadsFews
       - get_fews_locations
       - get_fews_thresholds
       - LoadsMatroos
       - get_matroos_locations
       - LoadsWaterwebservicesRWS
       - get_rws_webservices_locations
       - LoadsToMoments
       - LoadsWaterinfo
       - get_waterinfo_locations
       - get_waterinfo_thresholds
    - title: Dijkvak
      desc: Functies die betrekking hebben op dijkvakken
      package: toolbox_continu_inzicht.sections
      contents:
       - SectionsLoads
       - SectionsCriticalFailureprobability
       - SectionsTechnicalFailureprobability
       - SectionsMeasureFailureprobability
       - SectionsClassify
    - title: Fragility curves
      desc: Functies voor het berekenen en aanpassen van Fragility curve
      package: toolbox_continu_inzicht.fragility_curves
      contents:
       - FragilityCurveOvertopping
       - FragilityCurveOvertoppingMultiple
       - ShiftFragilityCurveOvertopping
       - ChangeCrestHeightFragilityCurveOvertopping
       - FragilityCurvePipingFixedWaterlevel
       - FragilityCurvePipingMultiple
       - CombineFragilityCurvesIndependent
       - CombineFragilityCurvesDependent
       - CombineFragilityCurvesWeightedSum
       - IntegrateFragilityCurve
       - IntegrateFragilityCurveMultiple
    - title: Inspectie resultaten
      desc: Invoer, verwerken en tonen van inspectie resultaten
      package: toolbox_continu_inzicht.inspections
      contents:
        - Filter
        - InspectionsToDatabase
        - ClassifyInspections
    - title: Continu Inzicht Adapters (invoer)
      desc: Invoer adapters voor Continu Inzicht meetstations/ dijkvak
      package: toolbox_continu_inzicht.base.adapters.input.continu_inzicht_postgresql
      contents:
       - input_measuringstation   # measuringstation
       - input_section            # section
       - input_fragilitycurve     # fragilitycurve
    - title: Continu Inzicht Adapters (uitvoer)
      desc: Uitvoer adapters voor Continu Inzicht meetstations/ dijkvak
      package: toolbox_continu_inzicht.base.adapters.output.continu_inzicht_postgresql
      contents:
       - output_measuringstation  # measuringstation
       - output_section           # section
       - output_calculation       # calculation
