[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "continu_inzicht_toolbox"
description = "Toolbox voor waterkeringbeheerders om risico's in kaart te brengen"
readme = "README.md"
authors = [
    { name = "David Haasnoot", email = "d.haasnoots@hkv.nl" },
    { name = "Guy Dupuits", email = "dupuits@hkv.nl" },
    { name = "Jerom Aerts", email = "j.aerts@hkv.nl" },
    { name = "Rolf Waterman", email = "r.watermans@hkv.nl" },
    { name = "Bart Thonus", email = "b.thonus@hkv.nl" },
    { name = "Marit Zethof", email = "m.zethof@hkv.nl" },
    
]

license = { text = "GPL-3.0-or-later" }

requires-python = ">=3.10"
dependencies = ["geopandas", "numpy", "pandas", "shapely"]
dynamic = ["version"]

[tool.hatch.version]
path = "continu_inzicht_toolbox/__init__.py"


[project.urls]
Documentation = "https://continu-inzicht.github.io/toolbox/"
Source = "https://github.com/continu-inzicht/toolbox"